apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: msdesa

commonLabels:
  app: api-sso
  component: backend
  owner: devops

patches:
  - path: configmap.yaml

images:
  - name: registry/group/image:tag
    newName: lasegunda.quay.com.ar/lasegunda/api-sso
    newTag: 1.3.0
